# Generated by Django 4.2.1 on 2023-06-09 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carCatalog', '0002_carcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcomment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
