# Generated by Django 4.2.1 on 2023-06-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carCatalog', '0007_alter_carcomment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
