# Generated by Django 4.2.1 on 2023-06-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carCatalog', '0008_rename_user_id_carcomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcomment',
            old_name='user',
            new_name='user_id',
        ),
    ]
