# Generated by Django 4.2.1 on 2023-06-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.svg', upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
