# Generated by Django 4.2.1 on 2023-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
